- name: Install Java
  apt:
    name: "{{ java_package }}"
    state: present
    update_cache: yes

- name: Install required packages
  apt:
    name: wget
    state: present

- name: Download Nexus
  get_url:
    url: "{{ nexus_download_url }}"
    dest: "/tmp/nexus.tar.gz"

- name: Extract Nexus
  unarchive:
    src: "/tmp/nexus.tar.gz"
    dest: "/tmp/"
    remote_src: yes
    creates: "/tmp/nexus-{{ nexus_version }}"

- name: Move Nexus
  command: mv /tmp/nexus-{{ nexus_version }} {{ nexus_install_dir }}
  args:
    creates: "{{ nexus_install_dir }}"

- name: Move sonatype-work
  command: mv /tmp/sonatype-work {{ nexus_data_dir }}
  args:
    creates: "{{ nexus_data_dir }}"

- name: Create Nexus user
  user:
    name: "{{ nexus_user }}"

- name: Set ownership
  file:
    path: "{{ item }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    recurse: yes
  loop:
    - "{{ nexus_install_dir }}"
    - "{{ nexus_data_dir }}"

- name: Configure nexus.rc
  lineinfile:
    path: "{{ nexus_install_dir }}/bin/nexus.rc"
    line: 'run_as_user="{{ nexus_user }}"'
    create: yes

- name: Fix shell
  replace:
    path: "{{ nexus_install_dir }}/bin/nexus"
    regexp: '^#!/bin/sh'
    replace: '#!/bin/bash'

- name: Configure JVM
  blockinfile:
    path: "{{ nexus_install_dir }}/bin/nexus.vmoptions"
    block: |
      -Xms{{ java_xms }}
      -Xmx{{ java_xmx }}
      -XX:MaxDirectMemorySize={{ java_max_direct }}

- name: Create systemd service
  template:
    src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable & Start Nexus
  service:
    name: nexus
    state: started
    enabled: yes
