# ---------------- DIRECTORIES ----------------
- name: Ensure base directory exists
  file:
    path: "{{ nexus_base_dir }}"
    state: directory
    mode: "{{ nexus_dir_mode }}"


# ---------------- DOWNLOAD ----------------
- name: Download Nexus
  command: >
    curl -fL "{{ nexus_download_url }}" -o {{ nexus_tmp_archive }}
  args:
    creates: "{{ nexus_tmp_archive }}"
  environment:
    http_proxy: "{{ http_proxy | default(omit) }}"
    https_proxy: "{{ https_proxy | default(omit) }}"


# ---------------- VALIDATE ----------------
- name: Check Nexus tar exists
  stat:
    path: "{{ nexus_tmp_archive }}"
  register: nexus_tar

- name: Fail if Nexus tar not found
  fail:
    msg: "Nexus tar file not downloaded!"
  when: not nexus_tar.stat.exists


# ---------------- EXTRACT ----------------
- name: Extract Nexus
  unarchive:
    src: "{{ nexus_tmp_archive }}"
    dest: "{{ nexus_base_dir }}/"
    remote_src: yes
    creates: "{{ nexus_base_dir }}/nexus-{{ nexus_version }}"


# ---------------- MOVE ----------------
- name: Move Nexus directory
  command: >
    mv {{ nexus_base_dir }}/nexus-{{ nexus_version }} {{ nexus_install_dir }}
  args:
    creates: "{{ nexus_install_dir }}"


- name: Move sonatype-work
  command: >
    mv {{ nexus_base_dir }}/sonatype-work {{ nexus_data_dir }}
  args:
    creates: "{{ nexus_data_dir }}"


# ---------------- USER & GROUP ----------------
- name: Ensure Nexus group exists
  group:
    name: "{{ nexus_group }}"
    state: present

- name: Create Nexus user
  user:
    name: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    shell: "{{ nexus_shell }}"
    create_home: yes


# ---------------- PERMISSIONS ----------------
- name: Set ownership
  file:
    path: "{{ item }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    state: directory
  loop:
    - "{{ nexus_install_dir }}"
    - "{{ nexus_data_dir }}"


# ---------------- CONFIGURATION ----------------
- name: Configure nexus.rc
  lineinfile:
    path: "{{ nexus_install_dir }}/bin/nexus.rc"
    line: 'run_as_user="{{ nexus_user }}"'
    create: yes


- name: Fix shell
  replace:
    path: "{{ nexus_install_dir }}/bin/nexus"
    regexp: '^#!/bin/sh'
    replace: '#!{{ nexus_shell }}'


- name: Configure JVM
  blockinfile:
    path: "{{ nexus_install_dir }}/bin/nexus.vmoptions"
    marker: "# {mark} ANSIBLE MANAGED JVM"
    block: |
      -Xms{{ java_xms }}
      -Xmx{{ java_xmx }}
      -XX:MaxDirectMemorySize={{ java_max_direct }}


# ---------------- SYSTEMD ----------------
- name: Create systemd service
  template:
    src: nexus.service.j2
    dest: "{{ nexus_systemd_path }}/{{ nexus_service_name }}.service"
  notify: Reload systemd
  when: ansible_service_mgr == "systemd"


- name: Enable & Start Nexus
  service:
    name: "{{ nexus_service_name }}"
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"
