---
- name: Download nexus_package 
  get_url: url=http://download.sonatype.com/nexus/3/nexus-{{ nexus_version }}-unix.tar.gz dest={{ nexus_download_dir }}/nexus-{{ nexus_version }}-unix.tar.gz
 
- name: Ensure Nexus o/s group exists
  group: name={{ nexus_os_group }} state=present
  when: nexus_create_os_group
 
- name: Ensure Nexus o/s user exists
  user: name={{ nexus_os_user }} group={{ nexus_os_group }} shell={{ nexus_os_user_shell }} state=present
  when: nexus_create_os_user
  
- name: Ensure Nexus installation directory exists
  file: path={{ nexus_installation_dir }} state=directory
 
- name: Unpack Nexus download
  unarchive:
    src={{ nexus_download_dir }}/nexus-{{ nexus_version }}-unix.tar.gz
    dest={{ nexus_installation_dir }}
    creates={{ nexus_installation_dir }}/nexus-{{ nexus_version }}
    force=no
    copy=false
    owner={{ nexus_os_user }}
    group={{ nexus_os_group }}
    mode="0755"

- name: Set permissions and ownership on some Nexus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nexus_os_user }}"
    group: "{{ nexus_os_group }}"
    mode: "0755"
    recurse: true
  with_items:
    - "{{ nexus_installation_dir }}/nexus-{{ nexus_version }}"
    - "{{ nexus_shared_dir }}"
    - "/var/run/nexus"

- name: Create a symbolic link to current directory
  file:
    src: "{{ nexus_installation_dir }}/nexus-{{ nexus_version }}"
    dest: "{{ nexus_installation_dir }}/current"
    state: link
    owner: "{{ nexus_os_user }}"
    group: "{{ nexus_os_group }}"
    mode: "0755"
  
- name: Configure port in nexus.properties
  lineinfile:
    dest={{ nexus_installation_dir }}/nexus-{{ nexus_version }}/etc/nexus-default.properties
    line=application-port={{ nexus_port }}
    regexp=application-port=.*
    state=present
  notify:
    - restart nexus

- name: Run nexus from user "{{ nexus_os_user }}"
  lineinfile:
    dest={{ nexus_installation_dir }}/current/bin/nexus.rc
    line=run_as_user="{{ nexus_os_user }}"
    regexp=#run_as_user=.*
    state=present
  notify:
    - restart nexus

- name: Configure data directory for nexus
  template:
    src: nexus.vmoptions.j2
    dest: "{{ nexus_installation_dir }}/nexus-{{ nexus_version }}/bin/nexus.vmoptions"
    owner: "{{ nexus_os_user }}"
    group: "{{ nexus_os_group }}"
    mode: '0755'
  notify:
    - restart nexus

- name: Start the nexus
  shell: "{{ nexus_installation_dir }}/current/bin/nexus start"
