---
# tasks file for Nexus role

- name: check Java version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | awk -F"_" '{print $1}'| sed 's/"//g'
  register: java_version

- name: Print message if correct version of java is not installed
  fail:
    msg: "java version is not compatible with {{ nexus_version }}"
  when: (java_version.stdout < "1.8")

- name: Checking nexus-{{ nexus_version }} directory at install path
  stat:
    path: "{{ nexus_installation_dir }}/nexus-{{ nexus_version }}"
  register: is_available

- name: Installing nexus 3
  include: install.yml
  when: is_available.stat.exists == False

- name: Including tasks for Ubuntu Family
  include_tasks: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Including tasks for CentOS Family
  include_tasks: EL.yml
  when: ansible_distribution == "CentOS"

- name: Including tasks for Rhel Family
  include_tasks: EL.yml
  when: ansible_distribution == "RedHat"  
