- debug:
    msg: "User={{ nexus_admin_user }}, Password={{ new_admin_password }}"
    
# ---------------- ROLES ----------------
- name: Get existing roles
  uri:
    url: "{{ nexus_url }}/service/rest/v1/security/roles"
    method: GET
    user: "{{ nexus_admin_user }}"
    password: "{{ new_admin_password }}"
    force_basic_auth: yes
  register: role_list
  retries: 5
  delay: 5
  until: role_list.status == 200

- name: Create Role
  uri:
    url: "{{ nexus_url }}/service/rest/v1/security/roles"
    method: POST
    user: "{{ nexus_admin_user }}"
    password: "{{ new_admin_password }}"
    force_basic_auth: yes
    body_format: json
    body:
      id: "{{ nexus_role_id }}"
      name: "{{ nexus_role_name }}"
      privileges: "{{ nexus_role_privileges }}"
      roles: "{{ nexus_role_inherited | default([]) }}"
  when: nexus_role_id not in (role_list.json | map(attribute='id') | list)

# ---------------- USERS ----------------
- name: Get existing users
  uri:
    url: "{{ nexus_url }}/service/rest/v1/security/users"
    method: GET
    user: "{{ nexus_admin_user }}"
    password: "{{ new_admin_password }}"
    force_basic_auth: yes
  register: user_list
  retries: 5
  delay: 5
  until: user_list.status == 200

- name: Create User
  uri:
    url: "{{ nexus_url }}/service/rest/v1/security/users"
    method: POST
    user: "{{ nexus_admin_user }}"
    password: "{{ new_admin_password }}"
    force_basic_auth: yes
    body_format: json
    body:
      userId: "{{ nexus_user_id }}"
      password: "{{ nexus_user_password }}"
      firstName: "{{ nexus_user_firstname }}"
      lastName: "{{ nexus_user_lastname }}"
      emailAddress: "{{ nexus_user_email }}"
      status: active
      roles: "{{ nexus_user_roles }}"
  no_log: true
  when: nexus_user_id not in (user_list.json | map(attribute='userId') | list)
